formatter: markdown

version: "~> 0.20"

content: |-
  {{ .Requirements }}

  ## Usage

  Basic usage of this module is as follows:

  ```hcl
    module "example" {
      {{"\t"}} source  = "git::https://<org>@dev.azure.com/<org>/<project>/_git/<module>?ref=<version>"

      {{- if .Module.RequiredInputs }}
      {{"\n\t"}} # Required variables
      {{- range .Module.RequiredInputs }}
      {{"\t"}} {{ .Name }}  = {{ .GetValue }}
      {{- end }}
      {{- end }}

      {{- if .Module.OptionalInputs }}
      {{"\n\t"}} # Optional variables
      {{- range .Module.OptionalInputs }}
      {{"\t"}} {{ .Name }}  = {{ .GetValue | printf "%s" }}
      {{- end }}
      {{- end }}
    }
  ```

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required

recursive:
  enabled: false

sections:
  hide: []
  show: []

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
